const { clientError, serverError } = require("./error");
const {
  signup,
  login,
  logout,
  addProject,
  allProjects,
  deletePost,
  getTasks,
  addTask,
  deleteComment,
  getUserInfo,
  allContacts,
  allUsers,
  getProjectInfo,
  restPassword,
  addAppointment,
  allAppointments,
  getAllStatus,
  getProjectInfoUsers,
  getProjectTechniques,
  postProjectUsers,
  addProjectTechniques,
  getUserProjects,
} = require("./api");

const {
  signupPage,
  loginPage,
  restPasswordPage,
  aboutUsPage,
  appointmentsPage,
  projectPage,
  currentProjectPage,
  supervisorProjectsPage,
  projectsPage,
  supervisorDashboardPage,
  oldProjectsPage,
  adminPage,
  contactsPage,
  studentProjectPage,
} = require("./pages");

module.exports = {
  clientError,
  serverError,
  signup,
  login,
  logout,
  signupPage,
  loginPage,
  restPasswordPage,
  aboutUsPage,
  appointmentsPage,
  projectPage,
  currentProjectPage,
  supervisorProjectsPage,
  projectsPage,
  addProject,
  allProjects,
  deletePost,
  getTasks,
  addTask,
  deleteComment,
  getUserInfo,
  allContacts,
  allUsers,
  getProjectInfo,
  restPassword,
  addAppointment,
  allAppointments,
  getAllStatus,
  getProjectInfoUsers,
  getProjectTechniques,
  postProjectUsers,
  addProjectTechniques,
  getUserProjects,
  supervisorDashboardPage,
  oldProjectsPage,
  adminPage,
  contactsPage,
  studentProjectPage,
};
